config/routes.rb
Supsf::Application.routes.draw do
  devise_for :users

  resources :categories

  resources :places do
    resources :comments
    collection do
      post 'filter' => 'places#filter'
    end
  end
   
  root :to => "places#index"

end

app/models/place.rb
# == Schema Information
#
# Table name: places
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  location    :string(255)
#  description :string(255)
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  image       :string(255)
#  latitude    :float
#  longitude   :float
#  gmaps       :boolean
#

class Place < ActiveRecord::Base
  attr_accessible :description, :location, :name, :category_id, :image
  belongs_to :category
  has_many :comments, dependent: :destroy
  
  mount_uploader :image, ImageUploader

  acts_as_gmappable

  def gmaps4rails_address
    "#{self.location}, San Francisco, United States" 
  end
  
  #def gmaps4rails_infowindow
  #  "#{self.name}"
  #end
  
  #def gmaps4rails_marker_picture
  #  {
  #   "picture" => "/assets/map_icons/#{self.category.identity}.png",
  #   "width" => 32,
  #   "height" => 37,
  #  }
  #end
  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # GET /places
  # GET /places.json  
  before_filter :authenticate_admin, only: [:new, :create, :edit, :update, :destroy]
  
  def authenticate_admin
    if !user_signed_in? 
      redirect_to new_user_session_path, flash: { error: "Vous devez vous connecter" }
      return
    end
    
    if !current_user.try(:admin?)
      redirect_to places_path, flash: { error: "Vous n'avez pas les droits suffisants" }
      return
    end
  end
  
  def filter
    @filtered_cat = params[:filter][:cat]
    if(@filtered_cat.empty?)
      @places = Place.all
    else
      @places = Place.where(category_id: @filtered_cat)
    end
    @json = define_json(@places)
    render :index
    
  end
  
  def index
    @places = Place.all
    #@json = @places.to_gmaps4rails
    @json = define_json(@places)
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id])
    @comment = Comment.new(place_id: @place.id)
    @json = Place.find(params[:id]).to_gmaps4rails

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/new
  # GET /places/new.json
  def new
    @place = Place.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(params[:place])

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render json: @place, status: :created, location: @place }
      else
        format.html { render action: "new" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /places/1
  # PUT /places/1.json
  def update
    @place = Place.find(params[:id])

    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end
  
  private
  
  def define_json(places)
    places.to_gmaps4rails do |place, marker|
      marker.infowindow render_to_string(:partial => "infowindow", :locals => { :place => place})
      marker.picture({
                      :picture  => "/assets/map_icons/#{place.category.identity}.png",
                      :width    => 32,
                      :height   => 37
                     })
      marker.title   place.name
      marker.json({ :id => place.id })
    end
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
		<%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image, "Image URL" %><br />
    <%= f.file_field :image %>
  </div>
	
	<% if(@place.image?) %>
	<div>
		<%= image_tag(@place.image, :alt => @place.name) %>
	</div>
	<% end  %>
		
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/_infowindow.html.erb
<%= image_tag(place.image.thumb, :alt => place.name, :class => "pull-left cadre-image") %>
<p><b><%= link_to place.name, place_path(place) %></b><br /> 
<%= link_to "#{pluralize(place.comments.count, 'commentaire', 'commentaires')}", place_path(place, :anchor => "comments") %>
<%= place.description %></p>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1 class="text-center">San Francisco Places</h1>

<%= gmaps("markers" => {"data" => @json}) %>
<br />

<%= form_for(filter_places_path, url: filter_places_path) do %>
	<div class="input-append">
		<%= collection_select :filter, :cat, Category.all, :id, :name, selected: @filtered_cat, include_blank: 'Tout' %>
		<%= submit_tag "Filtrer", class: "btn btn-primary" %>
	</div>
<% end %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="span6">
		<h1 class="center"><%= @place.name %></h1>
		<br />

		<p>
	  	<b>Catégorie :</b>
	  	<%= @place.category.name %>
		</p>
		<br />

		<p>
	  	<b>Description:</b>
	  	<%= @place.description %>
		</p>
	</div>
	
	<div class="span6">
		<%= image_tag(@place.image, :alt => @place.name, :class => "featurette-image pull-right cadre-image") %>
	</div>
</div>

<br />
<br />

<div class="row">
	<div class="span12">
		<%= gmaps("markers" => {"data" => @json}) %>
	</div>
</div>

<br />

<h3><a name="comments">Commentaires</a></h3>
<% if (@place.comments.count == 0) %>
<p>Soyez le premier à laisser un commentaire sur ce lieu !</p>
<% end %>
<% @place.comments.each do |comment| %>
	<p><strong>Par <%= comment.user.name %></strong> le <em><%= comment.updated_at %></em></p>
	<p><%= comment.content %></p>
	<p><%= link_to 'Destroy', place_comment_path(@place, comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
	<br />
<% end %>

<% if(user_signed_in?)  %>
<%= render 'shared/comment_form', place: @place %>
<% if(current_user.admin?) %>
<%= link_to 'Edit', edit_place_path(@place) %> |
<% end %>
<% else %>
<p>Vous devez vous <%= link_to 'connecter', new_user_session_path %> pour commenter</p>
<% end %>

<%= link_to 'Back', places_path %>